//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:43:10 AM CST 
//


package JAXB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for departmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="departmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="党组织"/>
 *     &lt;enumeration value="学生会"/>
 *     &lt;enumeration value="行政部门"/>
 *     &lt;enumeration value="物业部门"/>
 *     &lt;enumeration value="直属部门"/>
 *     &lt;enumeration value="院系"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "departmentType", namespace = "http://www.nju.edu.cn/schema")
@XmlEnum
public enum DepartmentType {

    党组织,
    学生会,
    行政部门,
    物业部门,
    直属部门,
    院系;

    public String value() {
        return name();
    }

    public static DepartmentType fromValue(String v) {
        return valueOf(v);
    }

}
