//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:43:10 AM CST 
//


package JAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for score complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="score">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NormalScore" type="{http://jw.nju.edu.cn/schema}normalScore"/>
 *         &lt;element name="TestScore" type="{http://jw.nju.edu.cn/schema}testScore"/>
 *         &lt;element name="FinalScore" type="{http://jw.nju.edu.cn/schema}finalScore"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "score", propOrder = {
    "normalScore",
    "testScore",
    "finalScore"
})
public class Score {

    @XmlElement(name = "NormalScore")
    protected int normalScore;
    @XmlElement(name = "TestScore")
    protected int testScore;
    @XmlElement(name = "FinalScore")
    protected int finalScore;

    /**
     * Gets the value of the normalScore property.
     * 
     */
    public int getNormalScore() {
        return normalScore;
    }

    /**
     * Sets the value of the normalScore property.
     * 
     */
    public void setNormalScore(int value) {
        this.normalScore = value;
    }

    /**
     * Gets the value of the testScore property.
     * 
     */
    public int getTestScore() {
        return testScore;
    }

    /**
     * Sets the value of the testScore property.
     * 
     */
    public void setTestScore(int value) {
        this.testScore = value;
    }

    /**
     * Gets the value of the finalScore property.
     * 
     */
    public int getFinalScore() {
        return finalScore;
    }

    /**
     * Sets the value of the finalScore property.
     * 
     */
    public void setFinalScore(int value) {
        this.finalScore = value;
    }

}
