//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:43:10 AM CST 
//


package JAXB;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Coursename" type="{http://jw.nju.edu.cn/schema}courseName"/>
 *         &lt;element name="score" type="{http://jw.nju.edu.cn/schema}Score" minOccurs="0"/>
 *         &lt;element name="teacher" type="{http://jw.nju.edu.cn/schema}Teacher" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CourseId" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "coursename",
    "score",
    "teacher"
})
@XmlRootElement(name = "Course1")
public class Course1 {

    @XmlElement(name = "Coursename", namespace = "", required = true)
    protected String coursename;
    @XmlElement(namespace = "")
    protected Double score;
    @XmlElement(namespace = "", required = true)
    protected List<String> teacher;
    @XmlAttribute(name = "CourseId")
    protected Integer courseId;

    /**
     * Gets the value of the coursename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * Sets the value of the coursename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoursename(String value) {
        this.coursename = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getScore() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setScore(Double value) {
        this.score = value;
    }

    /**
     * Gets the value of the teacher property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the teacher property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeacher().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTeacher() {
        if (teacher == null) {
            teacher = new ArrayList<String>();
        }
        return this.teacher;
    }

    /**
     * Gets the value of the courseId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCourseId() {
        return courseId;
    }

    /**
     * Sets the value of the courseId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCourseId(Integer value) {
        this.courseId = value;
    }

}
