//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:43:10 AM CST 
//


package JAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for course complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="course">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CourseName" type="{http://jw.nju.edu.cn/schema}courseName"/>
 *         &lt;element name="TeacherName" type="{http://jw.nju.edu.cn/schema}Teacher"/>
 *         &lt;element name="ClassRoom" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MyScore" type="{http://jw.nju.edu.cn/schema}score"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CourseID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "course", propOrder = {
    "courseName",
    "teacherName",
    "classRoom",
    "myScore"
})
public class Course {

    @XmlElement(name = "CourseName", required = true)
    protected String courseName;
    @XmlElement(name = "TeacherName", required = true)
    protected String teacherName;
    @XmlElement(name = "ClassRoom", required = true)
    protected String classRoom;
    @XmlElement(name = "MyScore", required = true)
    protected Score myScore;
    @XmlAttribute(name = "CourseID")
    protected String courseID;

    /**
     * Gets the value of the courseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the value of the courseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseName(String value) {
        this.courseName = value;
    }

    /**
     * Gets the value of the teacherName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * Sets the value of the teacherName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherName(String value) {
        this.teacherName = value;
    }

    /**
     * Gets the value of the classRoom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassRoom() {
        return classRoom;
    }

    /**
     * Sets the value of the classRoom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassRoom(String value) {
        this.classRoom = value;
    }

    /**
     * Gets the value of the myScore property.
     * 
     * @return
     *     possible object is
     *     {@link Score }
     *     
     */
    public Score getMyScore() {
        return myScore;
    }

    /**
     * Sets the value of the myScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Score }
     *     
     */
    public void setMyScore(Score value) {
        this.myScore = value;
    }

    /**
     * Gets the value of the courseID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseID() {
        return courseID;
    }

    /**
     * Sets the value of the courseID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseID(String value) {
        this.courseID = value;
    }

}
