//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.16 at 09:43:10 AM CST 
//


package JAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.nju.edu.cn/schema}personInfo"/>
 *         &lt;element ref="{http://jw.nju.edu.cn/schema}CourseList"/>
 *       &lt;/sequence>
 *       &lt;attribute name="StudentNO" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personInfo",
    "courseList"
})
@XmlRootElement(name = "StudentE")
public class StudentE {

    @XmlElement(namespace = "http://www.nju.edu.cn/schema", required = true)
    protected PersonInfo personInfo;
    @XmlElement(name = "CourseList", required = true)
    protected CourseList courseList;
    @XmlAttribute(name = "StudentNO", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String studentNO;

    /**
     * Gets the value of the personInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PersonInfo }
     *     
     */
    public PersonInfo getPersonInfo() {
        return personInfo;
    }

    /**
     * Sets the value of the personInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonInfo }
     *     
     */
    public void setPersonInfo(PersonInfo value) {
        this.personInfo = value;
    }

    /**
     * Gets the value of the courseList property.
     * 
     * @return
     *     possible object is
     *     {@link CourseList }
     *     
     */
    public CourseList getCourseList() {
        return courseList;
    }

    /**
     * Sets the value of the courseList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseList }
     *     
     */
    public void setCourseList(CourseList value) {
        this.courseList = value;
    }

    /**
     * Gets the value of the studentNO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStudentNO() {
        return studentNO;
    }

    /**
     * Sets the value of the studentNO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStudentNO(String value) {
        this.studentNO = value;
    }

}
